name: frontend

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: aws s3 sync ../udemy-github-actions/frontend s3://udemy-github-actions-tryu --exact-timestamps --region ap-northeast-1
