name: frontend

on:
  push:
    branches:
      - main
    # frontend配下と.github配下が変更された場合のみ実行
    paths:
      - "frontend/**"
      - ".github/**"

defaults:
  run:
    working-directory: frontend

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::249757025553:role/udemy-github-actions-frontend-deployment-role
          aws-region: ap-northeast-1

      - run: aws s3 sync . s3://udemy-github-actions-tryu --exact-timestamps --region ap-northeast-1
